local f = io.open('DREM.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 DREM.sh')
os.execute('killall -9 tg')
os.execute('rm -rf DREM.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('DREM.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 DREM.sh')
os.execute('screen ./DREM.sh')
